
- hosts: all
  tasks:
- name: Copy Java rpm file to server
  copy:
   src: /root/Desktop/ansible/jdk-8u171-linux-x64.rpm
   dest: /root/Desktop/jdk-8u171-linux-x64.rpm
- name: Install java package.
  yum:
   name : /root/Desktop/jdk-8u171-linux-x64.rpm
   state: present
- name: Set path for java file
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: 'JAVA_HOME'
    line: 'JAVA_HOME: /usr/java/jdk1.8.0_171-amd64/'
    dest: /etc/environment
    state: present
    regexp: 'PATH'
    line: 'PATH=/usr/java/jdk1.8.0_171-amd64/bin:$PATH'
